name: real_estate_app
description: "Flutter application for real estate app"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  flutter_gen: ^5.5.0+1
  stacked: ^3.4.2
  stacked_services: ^1.5.0
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  stacked_generator: ^1.6.0
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.5.0+1
  flutter_lints: ^3.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/
      - assets/images/
      - assets/icons/
  fonts:
    - family: Euclid
      fonts:
        - asset: assets/fonts/euclid-circular-a/Euclid-Circular-A-Regular.ttf
        - asset: assets/fonts/euclid-circular-a/Euclid-Circular-A-Medium.ttf
        - asset: assets/fonts/euclid-circular-a/Euclid-Circular-A-Bold.ttf
          weight: 500
        - asset: assets/fonts/euclid-circular-a/Euclid-Circular-A-SemiBold.ttf
          weight: 400
        - asset: assets/fonts/euclid-circular-a/Euclid-Circular-A-Light.ttf
    

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  null_safety: true # Optional (default: true)

  integrations:
    flutter_svg: true
